# Generated by Django 2.2.17 on 2020-12-29 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('date_livraison', models.DateTimeField(default=django.utils.timezone.now)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=9)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('designation_matiere', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(max_length=200)),
                ('num_bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_journal', models.PositiveIntegerField()),
                ('date_sorties', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('qte_sorties', models.PositiveIntegerField()),
                ('reference_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Matiere')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Matiere'),
        ),
    ]
